### ISSUE TITLE
关于 MultiTagFlowLayout 数据显示

### ISSUE THREAD

**Issue by Android-pengbo** [XueyiXia/TagFlowLayout#1]
当我创建数据（TestBean）为 500 个的时候，运行 demo  却只展示了 48 个 ，点击展开 有卡顿现象，

Uploading SVID_20240517_112023_1.mp4…

**Comment by XueyiXia** [comment]
> 当我创建数据（TestBean）为 500 个的时候，运行 demo 却只展示了 48 个 ，点击展开 有卡顿现象，
> 
> Uploading SVID_20240517_112023_1.mp4…

hi，你好，收到你得Issues,我check了，

1.fix  “当我创建数据（TestBean）为 500 个的时候，运行 demo 却只展示了 48 个” 的bug
2.点击展开 有卡顿现象，这个问题我测试了下，确实当创建很多数据的时候，会有一些卡顿，因为这个设计的原理一个容器重新计算View 的高度，还有一个动画效果，所以这块我进行了一些优化，你可以再试试看！
但是在实际开发中，可能并不会有那么多数据，所以这两个我算是fix,  and close it

最后，感谢你提的Issues！！
